Remove cleanup.sh Update fedora.sh Update server.sh Update tools.sh Change attributes of fonts.sh

diff --git a/run_onchange_fedora.sh.tmpl b/run_onchange_fedora.sh.tmpl
--- a/run_onchange_fedora.sh.tmpl
+++ b/run_onchange_fedora.sh.tmpl
@@ -1,4 +1,6 @@
-#!/bin/bash
+#!/usr/bin/env bash
+
+set -euo pipefail
 
 {{ if eq .chezmoi.osRelease.id "fedora" -}}
 
@@ -48,6 +50,12 @@ EOF
 EOF
     fi
 fi
+
+# Cleanup
+sudo dnf autoremove -y
+sudo dnf install clean-rpm-gpg-pubkey remove-retired-packages symlinks -y
+sudo clean-rpm-gpg-pubkey
+sudo symlinks -r -d /usr
 
 {{ if eq .chezmoi.osRelease.variantID "workstation" -}}
 # Install RPM Fusion & Terra
